apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: c8k4636a8-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-66f41fdf6a.l4eo.p3.openshiftapps.com/rhtap/rhtap-qe-java-springboot:9e8408c989d30641fe1d8ece351c2a2abf766df9@sha256:6357215b1eec3969c911bdfc996f8666d3290ddb340794c072e97edc274b0ce2
          name: container-image
